#!/usr/bin/env bash

img_name="$1"

if [ ! -f "/Users/richiethomas/Desktop/$img_name.png" ]; then
  echo "File does not exist!"
  exit 1
fi

cp "/Users/richiethomas/Desktop/$img_name.png" "/Users/richiethomas/Workspace/OpenSource/impostorsguides.github.io/assets/images"

if [[ 0 == "$?" ]]; then 
  echo "File created"
  exit 0
fi

echo "Copy failed!"
exit 1
